# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b"  # frozen: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "895ebb389825c29bd4e0addcf7579d6c69d199cc"  # frozen: v0.9.6
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/python-poetry/poetry
    rev: "bd500dd3bdfaec3de6894144c9cedb3a9358be84"  # frozen: 2.0.1
    hooks:
    -   id: poetry-check
        args: ["--lock"]
