# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: f0b5944bef86f50d875305821a0ab0d8c601e465  # frozen: v0.8.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/python-poetry/poetry
    rev: '8cad7a423b459871e9ed6094252b15c9ddb8a7dd'  # frozen: 2.0.0
    hooks:
    -   id: poetry-check
        args: ["--lock"]
